version: '2'
services:
  postgres:
    image: postgres:9.6
    volumes:
      - //d/BigDataPlayground/local/arf_pg_data:/var/lib/postgresql/data
    ports:
      - "5433"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      PGPORT: 5433
    restart: always
  airflow_with_spark:
    image: docker.io/anajaparidze/airflow_spark:airflow_2.1.4-spark_2.4.7
    ports:
      - "5433"
      - 8080:8080
    environment:
      AIRFLOW__CORE__FERNET_KEY: 8NE6O6RcTJpxcCkuKxOHOExzIJkXkeJKbRie03a69dI=
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow@postgres:5433/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor      
    restart: always
    command: ["bash", "-c", "echo '### Testing connection... '
                            && python test_db_conn.py 
                            && echo '### Running DB Init... '
                            && airflow db init 
                            && echo '### Starting scheduler... '
                            && airflow scheduler -D
                            && echo '### Sleeping 10 seconds... '                            
                            && sleep 10
                            && echo '### Starting webserver... '                            
                            && airflow webserver"]
    volumes:
      - //d/BigDataPlayground/local/dags:/airflow/dags
      - //d/BigDataPlayground/local/jobs:/airflow/jobs
      - //d/BigDataPlayground/local/data:/airflow/data    
      - airflow_logs:/airflow/logs/  

  jupyter:
      image: docker.io/anajaparidze/jupyter_spark_pandas:spark_2.4.0-pandas_1.1.5
      volumes:
        - //d/BigDataPlayground/local/notebooks:/jupyter
      user: root
      container_name: jupyter
      hostname: jupyter
      ports:
        - 8888:8888             
      
volumes:
  airflow_logs: {}